name: CI Workflow
on: [ push ]

jobs:
  unit-tests:
    name: Unit tests with Thread Sanitizer
    runs-on: [ 'Linux' ]
    strategy:
      matrix:
        build-type:
          - asan
          - tsan
          - msan
          - ubsan

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up SSH key for docker build
        run: echo "${{ secrets.SSH_DEPLOY_SECRET }}" > deploy-ssh-key

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run inside container
        uses: docker/build-push-action@v6
        with:
          context: .
          ssh: default=deploy-ssh-key
          file: docker/tests.dockerfile
          cache-from: type=local,src=/tmp/buildx-cache
          cache-to: type=local,dest=/tmp/buildx-cache,mode=max
          build-args: |
            CMAKE_BUILD_TYPE=${{matrix.build-type}}
      # https://github.com/docker/build-push-action/issues/252
      - name: Trim cache to size
        run: bash .github/scripts/delete-oldest-until-size.sh /tmp/buildx-cache 25000000000
